name: check syntax, lint and static security analysis terraform code

on:
  pull_request:
    paths:
    - 'challenge-3/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: terraform validate
        uses: dflook/terraform-validate@v1
        with:
          path: challenge-3
      - name: tflint
        uses: reviewdog/action-tflint@v1
        with:
          github_token: ${{ secrets.github_token }}
          working_directory: "challenge-3"
          tflint_init: true
          fail_on_error: "false"
          filter_mode: "nofilter"
          flags: "-c .tflint.hcl"
      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          soft_fail: true
          working_directory: challenge-3